name: Checkout

on: [push]

jobs: 
  checkout-and-display-files:
    runs-on: ubuntu-latest
    steps:
      - name: List files Before
        run: ls -a
      - name: Checkout
        run: |
          git init
          git remote add origin "https://$GITHUB_ACTOR:${{secrets.GITHUB>TOKEN}}@github.com/$GITHUB_REPOSITORY.git"
          git fetch origin
          git checkout main
      - name: Lists file after
        run: ls -a
        

