name: Pull-Request Comment
on:
    pull_request_target:
        types: [opened]
jobs:
    pr-comment:
        runs-on: ubuntu-latest
        steps: 
            - name: Comment on new pr
              uses: actions/github-script@v6
              with:
               script: |
                 github.rest.issues.createComment({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    issue_number,
                    body,
                 });
            
